In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [7, 43, 65]]) #создание двумерного массива
a

array([[ 1,  2,  3],
       [ 7, 43, 65]])

In [26]:
b = np.arange(2, 7) #создание одномерного массива из чисел от 2 до 6 включительно
b

array([2, 3, 4, 5, 6])

In [ ]:
c = np.zeros((5, 3)) #создание массива из нулей
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
d = np.ones((2, 3)) #создание массива из едениц
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
d.dtype #вывод типа содеожащихся данных

dtype('float64')

In [22]:
d.shape #вывод формы массива

(2, 3)

In [30]:
a[0, 1] #вывод 2-го элемента 1-ой строки

np.int64(2)

In [33]:
a[0, 1:3] #вывод с 1-го по 3-ий эл-т 1-й строки

array([2, 3])

In [34]:
d * 7 + a #умножаем массив d на 7 и складываем с массивом а

array([[ 8.,  9., 10.],
       [14., 50., 72.]])

In [37]:
np.mean(a) #средняя величина массива а

np.float64(20.166666666666668)